version: '3'

services:
  php:
    container_name: laravel-spa-php-1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      # - ./php.ini:/etc/php/8.1/apache2/php.ini
    ports:
      - "8082:80"

