version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      # - ./php.ini:/etc/php/8.1/apache2/php.ini
    ports:
      - "8082:80"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_HOST: 172.17.0.1
      MYSQL_ROOT_PASSWORD: Aa!22071990
      MYSQL_DATABASE: dating
      MYSQL_USER: vitik
      MYSQL_PASSWORD: Aa!11111
    volumes:
      - mysql_data:/var/lib/mysql
      - .docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
volumes:
  mysql_data:
    driver: local

